#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTAINER_NAME="${OPENPROJECT_CONTAINER_NAME:-uac-openproject}"
SEED_FILE="$SCRIPT_DIR/openproject_dev_seed.rb"

OPENPROJECT_DEV_LOGIN="${OPENPROJECT_DEV_LOGIN:-UAC}"
OPENPROJECT_DEV_PASSWORD="${OPENPROJECT_DEV_PASSWORD:-uac123}"
OPENPROJECT_DEV_FIRSTNAME="${OPENPROJECT_DEV_FIRSTNAME:-$OPENPROJECT_DEV_LOGIN}"
OPENPROJECT_DEV_LASTNAME="${OPENPROJECT_DEV_LASTNAME:-Local}"
OPENPROJECT_DEV_EMAIL="${OPENPROJECT_DEV_EMAIL:-uac@local.test}"
OPENPROJECT_DEV_ADMIN="${OPENPROJECT_DEV_ADMIN:-true}"

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER_NAME"; then
  echo "OpenProject container '$CONTAINER_NAME' is not running."
  exit 1
fi

docker cp "$SEED_FILE" "$CONTAINER_NAME":/tmp/openproject_dev_seed.rb >/dev/null

docker exec \
  -e OPENPROJECT_DEV_LOGIN="$OPENPROJECT_DEV_LOGIN" \
  -e OPENPROJECT_DEV_PASSWORD="$OPENPROJECT_DEV_PASSWORD" \
  -e OPENPROJECT_DEV_FIRSTNAME="$OPENPROJECT_DEV_FIRSTNAME" \
  -e OPENPROJECT_DEV_LASTNAME="$OPENPROJECT_DEV_LASTNAME" \
  -e OPENPROJECT_DEV_EMAIL="$OPENPROJECT_DEV_EMAIL" \
  -e OPENPROJECT_DEV_ADMIN="$OPENPROJECT_DEV_ADMIN" \
  "$CONTAINER_NAME" \
  bash -lc 'bin/rails runner /tmp/openproject_dev_seed.rb'

